config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
    resources :likes
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to posts_path
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @like = Like.new
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.haml
= form_for [@post, @comment] do |f|
  = f.label :content
  = f.text_area :content
  = f.submit 'Leave Comment'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/posts/index.html.haml
- if user_signed_in?
  = link_to "Sign out", destroy_user_session_path, method: :delete
- else
  = link_to "Sign in", new_user_session_path
  = link_to "Sign up", new_user_registration_path

= link_to "Add a post", new_post_path

- if @posts.any?
  - @posts.each do |post|
    %h3= image_tag post.image.url(:medium)
    %h3= post.description

    - if post.comments.any?
      %ul
        - post.comments.each do |comment|
          %li= comment.content
    
    = link_to "Comment", new_post_comment_path(post)
    = link_to "Like", new_post_like_path(post)
- else
  %p No posts yet

app/views/posts/new.html.haml
%p Post your image here.

= form_for @post, html: { multipart: true } do |f|
  = f.file_field :image
  = f.text_field :description
  = f.submit